// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class edithstingservicetbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edithstingservicetbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202011040656599_edithstingservicetbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
